'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const oceans=[
 {id:'pacific',name:'Тихий океан',short:'Тихий',area:178.6,color:'#187d8d',center:[-155,0],kicker:'Самый большой и самый глубокий',text:'Тихий океан занимает почти половину площади Мирового океана. Его площадь больше площади всей суши Земли. На карте ищи его между Евразией и Австралией с одной стороны и Америкой — с другой.',insight:'Тихий океан — самый большой. На него приходится почти половина площади Мирового океана.'},
 {id:'atlantic',name:'Атлантический океан',short:'Атлантический',area:91.6,color:'#d2aa67',center:[-35,10],kicker:'Вытянут с севера на юг',text:'Атлантический океан по площади примерно вдвое меньше Тихого. На западе его обрамляют Северная и Южная Америка, на востоке — Евразия и Африка. Он сильно вытянут с севера на юг.',insight:'Атлантический океан занимает второе место по площади. Он примерно вдвое меньше Тихого.'},
 {id:'indian',name:'Индийский океан',short:'Индийский',area:76.2,color:'#82ad91',center:[78,-24],kicker:'Почти целиком в Южном полушарии',text:'Индийский океан расположен между Африкой, Евразией, Австралией и Антарктидой в принятом в параграфе делении на четыре океана. Почти весь он находится в Южном полушарии.',insight:'Индийский океан меньше Атлантического, но значительно больше Северного Ледовитого.'},
 {id:'arctic',name:'Северный Ледовитый океан',short:'Северный Ледовитый',area:14.7,color:'#9abcc9',center:[0,85],kicker:'Самый маленький из четырёх',text:'Северный Ледовитый океан расположен вокруг Северного полюса, у берегов Евразии и Северной Америки. Это самый маленький и самый холодный из четырёх океанов, описанных в параграфе.',insight:'Северный Ледовитый — самый маленький океан. На диаграмме ему соответствует самый небольшой сектор.'}
];
const format=n=>n.toLocaleString('ru-RU',{maximumFractionDigits:1});
let selectedOcean=0, pageId='oceans', mapMode=false, rotation=[155,-8,0], globeProjection, globePath, canvas=$('#world'),ctx=canvas.getContext('2d'),cw=0,ch=0;
let globeAnim=0;
function go(id){if(!$('#'+id)||!$('#'+id).classList.contains('page'))return;pageId=id;$$('.page').forEach(el=>{el.hidden=el.id!==id;el.classList.toggle('active',el.id===id)});$$('.bottom-nav button').forEach(b=>{const on=b.dataset.go===id;b.classList.toggle('active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});history.replaceState(null,'','#'+id);window.scrollTo({top:0,behavior:'instant'});if(id==='oceans')requestAnimationFrame(resizeGlobe);if(id==='compare')renderChart();}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
$('.brand').addEventListener('click',e=>{e.preventDefault();go('oceans')});
$('#explore').addEventListener('click',()=>$('#ocean-selection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}));
const dialog=$('#sources-dialog');$('#sources-open').onclick=$('#sources-footer').onclick=()=>dialog.showModal();$('#sources-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
$('#ocean-buttons').innerHTML=oceans.map((o,i)=>`<button class="ocean-button" data-ocean="${i}" style="--ocean-color:${o.color}" aria-pressed="false"><span class="ocean-dot"></span><span class="ocean-arrow">↗</span><b>${o.short}</b><small>${format(o.area)} млн км²</small></button>`).join('');
$$('[data-ocean]').forEach(b=>b.onclick=()=>selectOcean(+b.dataset.ocean,true));
function selectOcean(index,turn=false){selectedOcean=index;const o=oceans[index];$$('[data-ocean]').forEach(b=>{const on=+b.dataset.ocean===index;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});$('#ocean-kicker').textContent=o.kicker;$('#ocean-name').textContent=o.name;$('#ocean-text').textContent=o.text;$('#ocean-area').textContent=format(o.area);if($('#quick-ocean-kicker'))$('#quick-ocean-kicker').textContent=o.kicker;if($('#quick-ocean-name'))$('#quick-ocean-name').textContent=o.name;if($('#quick-ocean-text'))$('#quick-ocean-text').textContent=o.text;if($('#quick-ocean-area'))$('#quick-ocean-area').textContent=format(o.area);canvas.setAttribute('aria-label',`Глобус: выбран ${o.name}. ${o.kicker}. Для выбора доступны кнопки океанов.`);if(turn&&!mapMode)turnTo([-o.center[0],-o.center[1],0]);else drawWorld();if(pageId==='compare')renderChart();}
function turnTo(target){cancelAnimationFrame(globeAnim);if(matchMedia('(prefers-reduced-motion: reduce)').matches){rotation=target;drawWorld();return}let from=[...rotation];let dx=((target[0]-from[0]+540)%360)-180;let start=performance.now();function tick(t){let k=Math.min(1,(t-start)/700);let ease=1-Math.pow(1-k,3);rotation=[from[0]+dx*ease,from[1]+(target[1]-from[1])*ease,0];drawWorld();if(k<1)globeAnim=requestAnimationFrame(tick)}globeAnim=requestAnimationFrame(tick)}
function resizeGlobe(){if(pageId!=='oceans')return;const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;cw=r.width;ch=r.height;let dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(cw*dpr);canvas.height=Math.round(ch*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);drawWorld()}
function drawWorld(){if(!cw||!window.d3||!window.OCEAN_LAND)return;ctx.clearRect(0,0,cw,ch);const radius=Math.min(cw*.445,ch*.43);globeProjection=mapMode?d3.geoEquirectangular().translate([cw/2,ch/2]).scale((cw-18)/(2*Math.PI)).precision(.4):d3.geoOrthographic().translate([cw/2,ch/2]).scale(radius).rotate(rotation).clipAngle(90).precision(.3);globePath=d3.geoPath(globeProjection,ctx);
 ctx.beginPath();globePath({type:'Sphere'});let oceanGrad=ctx.createLinearGradient(0,0,cw,ch);oceanGrad.addColorStop(0,'#3b98a5');oceanGrad.addColorStop(.55,'#1c7185');oceanGrad.addColorStop(1,'#0e4e68');ctx.fillStyle=oceanGrad;ctx.fill();ctx.save();ctx.clip();ctx.beginPath();globePath(d3.geoGraticule10());ctx.strokeStyle='#b8e6e021';ctx.lineWidth=.6;ctx.stroke();ctx.beginPath();globePath(window.OCEAN_LAND);ctx.fillStyle='#b8cbb0';ctx.fill();ctx.strokeStyle='#d0ddbc';ctx.lineWidth=.45;ctx.stroke();ctx.beginPath();globePath({type:'LineString',coordinates:[[-180,0],[-120,0],[-60,0],[0,0],[60,0],[120,0],[180,0]]});ctx.strokeStyle='#e3ead34a';ctx.setLineDash([3,4]);ctx.lineWidth=.8;ctx.stroke();ctx.setLineDash([]);ctx.restore();
 if(!mapMode){let shade=ctx.createRadialGradient(cw/2-radius*.38,ch/2-radius*.5,radius*.15,cw/2,ch/2,radius);shade.addColorStop(0,'#effff510');shade.addColorStop(.72,'#001a2700');shade.addColorStop(1,'#00152666');ctx.beginPath();ctx.arc(cw/2,ch/2,radius,0,Math.PI*2);ctx.fillStyle=shade;ctx.fill();ctx.beginPath();ctx.arc(cw/2,ch/2,radius+1,0,Math.PI*2);ctx.strokeStyle='#a6dbd777';ctx.lineWidth=1.5;ctx.stroke()}
 oceans.forEach((o,i)=>{let center=globeProjection.invert([cw/2,ch/2]);if(!mapMode&&d3.geoDistance(o.center,center)>Math.PI/2-.08)return;const p=globeProjection(o.center);const active=i===selectedOcean;ctx.beginPath();ctx.arc(p[0],p[1],active?6:4,0,Math.PI*2);ctx.fillStyle=active?'#f5d291':'#dff1e6';ctx.fill();ctx.beginPath();ctx.arc(p[0],p[1],active?11:8,0,Math.PI*2);ctx.strokeStyle=active?'#f5d29188':'#dff1e655';ctx.lineWidth=1;ctx.stroke();if(active||mapMode){let label=o.short;ctx.font=`${active?'600':'400'} ${mapMode&&cw<400?9:11}px Segoe UI, Arial`;let width=ctx.measureText(label).width+16;let x=Math.max(3,Math.min(cw-width-3,p[0]-width/2));let y=p[1]+16;if(y+24>ch)y=p[1]-36;ctx.fillStyle='#053744ee';ctx.beginPath();ctx.roundRect(x,y,width,25,6);ctx.fill();ctx.fillStyle=active?'#f7d99d':'#e1eee7';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,x+width/2,y+12)}});
}
$('#globe-mode').onclick=()=>setMapMode(false);$('#map-mode').onclick=()=>setMapMode(true);
function setMapMode(value){mapMode=value;$('#globe-mode').classList.toggle('selected',!value);$('#map-mode').classList.toggle('selected',value);$('#globe-mode').setAttribute('aria-pressed',!value);$('#map-mode').setAttribute('aria-pressed',value);$('#globe-hint').textContent=value?'Нажми на маркер океана':'↔ Поворачивай пальцем или мышью';drawWorld()}
$('#reset-globe').onclick=()=>{if(mapMode)selectOcean(0);else turnTo([-oceans[selectedOcean].center[0],-oceans[selectedOcean].center[1],0])};
let drag=null;
canvas.addEventListener('pointerdown',e=>{cancelAnimationFrame(globeAnim);drag={x:e.clientX,y:e.clientY,rot:[...rotation],moved:false};if(e.pointerType!=='touch'){canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging')}});
canvas.addEventListener('pointermove',e=>{if(!drag||mapMode)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;if(drag.moved){rotation=[drag.rot[0]+dx*.35,Math.max(-90,Math.min(90,drag.rot[1]-dy*.35)),0];drawWorld()}});
canvas.addEventListener('pointerup',e=>{if(!drag)return;if(!drag.moved){let r=canvas.getBoundingClientRect(),pos=[e.clientX-r.left,e.clientY-r.top];let nearest=-1,dist=32;oceans.forEach((o,i)=>{if(!mapMode&&d3.geoDistance(o.center,globeProjection.invert([cw/2,ch/2]))>Math.PI/2)return;let p=globeProjection(o.center),d=Math.hypot(p[0]-pos[0],p[1]-pos[1]);if(d<dist){nearest=i;dist=d}});if(nearest>=0)selectOcean(nearest,false)}drag=null;canvas.classList.remove('dragging')});canvas.addEventListener('pointercancel',()=>{drag=null;canvas.classList.remove('dragging')});new ResizeObserver(resizeGlobe).observe(canvas);
function renderChart(){let total=d3.sum(oceans,o=>o.area);let pie=d3.pie().sort(null).value(o=>o.area)(oceans),arc=d3.arc().innerRadius(100).outerRadius(144),selected=oceans[selectedOcean];$('#donut').innerHTML=`<svg viewBox="0 0 330 330" aria-label="Площади четырёх океанов"><g transform="translate(165,165)">${pie.map((p,i)=>`<path class="arc" data-arc="${i}" d="${arc(p)}" fill="${p.data.color}" stroke="white" stroke-width="${selectedOcean===i?5:2}" tabindex="0" role="button" aria-label="${p.data.name}, ${format(p.data.area)} миллиона квадратных километров"></path>`).join('')}<text y="-18" text-anchor="middle" font-family="Georgia" font-size="40" fill="#113e48">${format(selected.area)}</text><text y="9" text-anchor="middle" font-family="Segoe UI" font-size="12" fill="#527079">млн км²</text><text y="38" text-anchor="middle" font-family="Segoe UI" font-size="11" fill="#113e48">${selected.short}</text></g></svg>`;$$('[data-arc]').forEach(p=>{p.onclick=()=>selectOcean(+p.dataset.arc);p.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectOcean(+p.dataset.arc)}}});$('#area-bars').innerHTML=oceans.map((o,i)=>`<button class="area-row ${i===selectedOcean?'active':''}" data-bar="${i}" aria-pressed="${i===selectedOcean}" style="--ocean-color:${o.color}"><span class="bar-label"><span>${o.short}</span><strong>${format(o.area)}</strong></span><div class="bar-track"><div class="bar-fill" style="width:${o.area/oceans[0].area*100}%"></div></div></button>`).join('');$$('[data-bar]').forEach(b=>b.onclick=()=>selectOcean(+b.dataset.bar));$('#chart-insight').textContent=selected.insight;$('#donut').setAttribute('aria-label',`Диаграмма площадей. ${oceans.map(o=>o.name+': '+format(o.area)).join('; ')} млн км².`)}
const coastData=[
 {name:'Внутреннее море',text:'Море — часть океана, которая отличается от него свойствами вод и глубинами. Внутреннее море глубоко вдаётся в сушу и связано с океаном проливами.',example:'Примеры: Средиземное, Чёрное, Азовское, Балтийское, Красное моря.',kind:'inland'},
 {name:'Окраинное море',text:'Окраинное море расположено у окраины материка. Оно часто отделено от основной части океана островами или полуостровами.',example:'Примеры: Баренцево, Карское, Чукотское, Охотское, Японское моря.',kind:'marginal'},
 {name:'Залив',text:'Залив — часть океана или моря, которая вдаётся в сушу. Посмотри, как берег огибает водное пространство.',example:'Примеры: Бенгальский, Мексиканский, Персидский, Финский заливы.',kind:'bay'},
 {name:'Пролив',text:'Пролив — узкий, вытянутый участок воды. Он соединяет две акватории и одновременно разделяет участки суши.',example:'Например, Гибралтарский пролив соединяет Атлантический океан и Средиземное море.',kind:'strait'}
];
$('#coast-tabs').innerHTML=coastData.map((c,i)=>`<button data-coast="${i}" aria-pressed="false">${c.name}</button>`).join('');$$('[data-coast]').forEach(b=>b.onclick=()=>selectCoast(+b.dataset.coast));
function selectCoast(i){let c=coastData[i];$$('[data-coast]').forEach(b=>{b.classList.toggle('active',+b.dataset.coast===i);b.setAttribute('aria-pressed',+b.dataset.coast===i)});$('#coast-name').textContent=c.name;$('#coast-description').textContent=c.text;$('#coast-example').textContent=c.example;$('#coast-picture').innerHTML=coastSVG(c.kind)}
function coastSVG(kind){let common=`<defs><pattern id="waves" width="45" height="32" patternUnits="userSpaceOnUse"><path d="M8 20q8-6 16 0t16 0" stroke="#fff" opacity=".18" fill="none"/></pattern></defs><rect width="560" height="350" fill="#73b5c1"/><rect width="560" height="350" fill="url(#waves)"/>`;let land='fill="#c3cba2" stroke="#edf0cb" stroke-width="5"';let shapes='',labels='';
 if(kind==='inland'){shapes=`<path d="M0 0H560V350H0V215L145 213Q183 212 204 228C241 270 367 268 395 206C436 140 355 88 287 102C214 112 211 173 170 178L0 174Z" ${land}/><path d="M208 190C220 124 321 91 379 144C444 209 357 262 283 242C225 228 236 204 208 190Z" fill="#e6c17b" opacity=".45"/><path d="M70 194H192" stroke="#fff8dd" stroke-width="3" stroke-dasharray="7 7"/>`;labels=`<text x="294" y="187">МОРЕ</text><text x="82" y="151" class="tiny">ОКЕАН</text><text x="281" y="52" class="land-label">СУША</text><text x="122" y="238" class="tiny">пролив</text>`}
 if(kind==='marginal'){shapes=`<path d="M0 0H325Q315 43 244 66T229 155Q295 207 230 262T247 350H0Z" ${land}/><path d="M322 74q35 8 14 45q-32 5-14-45M355 143q37 8 9 47q-26-7-9-47M328 213q41-5 27 44q-37 18-27-44" ${land}/><ellipse cx="282" cy="170" rx="62" ry="107" fill="#e6c17b" opacity=".32"/>`;labels=`<text x="110" y="172" class="land-label">МАТЕРИК</text><text x="285" y="174" class="tiny">МОРЕ</text><text x="459" y="177">ОКЕАН</text><text x="376" y="300" class="tiny">острова</text>`}
 if(kind==='bay'){shapes=`<path d="M0 0H560V70Q440 44 373 120Q308 166 261 126Q178 85 136 139Q90 202 165 231Q226 261 292 231Q361 221 422 281L470 350H0Z" ${land}/><path d="M359 154Q316 176 256 151Q181 109 154 165Q132 213 207 226Q279 235 334 208Z" fill="#e6c17b" opacity=".55"/>`;labels=`<text x="223" y="191">ЗАЛИВ</text><text x="430" y="191">ОКЕАН</text><text x="215" y="63" class="land-label">СУША</text>`}
 if(kind==='strait'){shapes=`<path d="M0 0H560V73Q438 52 365 135L345 157Q290 170 234 139L198 105Q105 57 0 90Z" ${land}/><path d="M0 350H560V260Q444 284 369 225L341 201Q287 188 241 211L205 243Q102 290 0 260Z" ${land}/><path d="M203 157Q288 198 376 174" fill="none" stroke="#f1d39b" stroke-width="20" opacity=".7"/><path d="M80 181H468" stroke="#f8fbef" stroke-width="3" stroke-dasharray="7 7"/>`;labels=`<text x="275" y="123" class="tiny">ПРОЛИВ</text><text x="87" y="217" class="tiny">АКВАТОРИЯ 1</text><text x="466" y="217" class="tiny">АКВАТОРИЯ 2</text><text x="275" y="46" class="land-label">СУША</text><text x="275" y="310" class="land-label">СУША</text>`}
 return `<svg viewBox="0 0 560 350" role="img" aria-label="Условная схема: ${coastData.find(c=>c.kind===kind).name}"><style>.coast-picture text{font:600 15px 'Segoe UI',sans-serif;fill:#124755;text-anchor:middle;letter-spacing:1px}.coast-picture .tiny{font-size:12px;letter-spacing:.3px}.coast-picture .land-label{fill:#566e50;font-size:13px}</style>${common}${shapes}${labels}<rect x="15" y="314" width="127" height="23" rx="6" fill="#f5f5e7d9"/><text x="78" y="330" style="font-size:9px;letter-spacing:.5px">УСЛОВНАЯ СХЕМА</text></svg>`;
}
const straits=[{name:'Гибралтарский',water:'Атлантический океан ↔ Средиземное море',land:'Африка ↔ Евразия',note:'Узкий проход между двумя материками.'},{name:'Берингов',water:'Тихий ↔ Северный Ледовитый океан',land:'Евразия ↔ Северная Америка',note:'Связывает два океана и разделяет два материка.'},{name:'Магелланов',water:'Атлантический ↔ Тихий океан',land:'Южная Америка ↔ Огненная Земля',note:'Проходит у южной оконечности Южной Америки.'},{name:'Татарский',water:'Японское ↔ Охотское море',land:'Евразия ↔ Сахалин',note:'Водная связь с Охотским морем проходит через пролив Невельского, Амурский лиман и Сахалинский залив. В параграфе выделено: отделяет Сахалин от Евразии.'},{name:'Мозамбикский',water:'Воды Индийского океана',land:'Африка ↔ Мадагаскар',note:'В параграфе назван самым длинным проливом мира.'}];
$('#strait-buttons').innerHTML=straits.map((s,i)=>`<button data-strait="${i}" aria-pressed="false">${s.name}</button>`).join('');$$('[data-strait]').forEach(b=>b.onclick=()=>selectStrait(+b.dataset.strait));function selectStrait(i){let s=straits[i];$$('[data-strait]').forEach(b=>{b.classList.toggle('active',+b.dataset.strait===i);b.setAttribute('aria-pressed',+b.dataset.strait===i)});$('#strait-water').textContent=s.water;$('#strait-land').textContent=s.land;$('#strait-note').textContent=s.note}
function creatureSVG(type){const shapes={star:'<path d="M60 9Q65 9 70 37L75 44 105 41Q118 43 101 56L81 70 88 101Q89 113 78 103L59 83 35 102Q22 109 29 96L38 68 14 49Q4 37 20 40L47 43Z" fill="#dca578" stroke="#f1c9a4" stroke-width="2"/><path d="M59 54L61 22M62 58L98 47M65 64L82 94M55 66L34 94M53 58L23 48" fill="none" stroke="#bc815c" stroke-width="3" stroke-linecap="round"/><g fill="#f4d2ab"><circle cx="59" cy="60" r="4"/><circle cx="59" cy="36" r="2"/><circle cx="83" cy="53" r="2"/><circle cx="72" cy="80" r="2"/><circle cx="43" cy="83" r="2"/></g>',jelly:'<path d="M34 59q-8 17 5 28t-2 24M48 61q13 13 0 29t2 24M64 62q-9 19 5 28t0 24M80 58q12 21 0 36" fill="none" stroke="#a4cbe0" stroke-width="4" stroke-linecap="round"/><path d="M20 57C18 2 99 2 100 57Q90 69 79 59Q68 71 59 60Q48 71 39 59Q29 67 20 57" fill="#b6cde6" stroke="#dce9f1" stroke-width="2"/><path d="M32 45Q35 22 56 20" fill="none" stroke="#f0f5fa" stroke-width="4" stroke-linecap="round"/><ellipse cx="62" cy="46" rx="20" ry="14" fill="#829ec8" opacity=".4"/>',fish:'<path d="M20 61C32 27 79 29 93 53L113 38 109 80 91 67C75 95 37 92 20 61" fill="#dfa958" stroke="#f3d08e" stroke-width="2"/><path d="M52 35L61 20 78 36M52 86L65 100 80 82" fill="#be7d42"/><path d="M70 38q-13 24 0 47" stroke="#f4d7a2" stroke-width="5" fill="none"/><circle cx="36" cy="55" r="4" fill="#183c4b"/><path d="M18 61H28M48 64l13 9V54Z" fill="#bd8147"/>',crab:'<path d="M29 58L10 44 7 27M28 68L7 77 5 90M40 82L25 97 20 111M78 82L94 97 101 110M91 67L112 77 115 90M89 58L110 44 113 27" fill="none" stroke="#c47c64" stroke-width="6" stroke-linecap="round"/><path d="M7 29Q-5 9 11 8L15 20 22 8Q35 19 18 34M106 30Q92 11 105 7L111 18 119 7Q127 28 113 35" fill="#cf8b70"/><ellipse cx="60" cy="66" rx="35" ry="25" fill="#dcaa86"/><path d="M47 43L45 33M73 43L75 33" stroke="#a36c52" stroke-width="6" stroke-linecap="round"/><circle cx="45" cy="32" r="4" fill="#233b42"/><circle cx="75" cy="32" r="4" fill="#233b42"/><path d="M40 68q20 12 40 0" stroke="#c99170" fill="none" stroke-width="3"/>',anemone:'<ellipse cx="61" cy="104" rx="36" ry="10" fill="#9faaa1"/><path d="M44 97L48 64H76L82 99Q65 110 44 97" fill="#b87d6d"/>'+Array.from({length:9},(_,i)=>`<path d="M61 74Q${14+i*11} 51 ${15+i*11} ${18+Math.abs(4-i)*6}" stroke="${i%2?'#e2ae9b':'#b7b590'}" stroke-width="7" fill="none" stroke-linecap="round"/>`).join('')+'<ellipse cx="61" cy="67" rx="17" ry="9" fill="#e8c4a3"/>',kelp:'<path d="M60 110Q53 60 60 15M58 106Q23 80 29 34M63 104Q94 72 92 34" fill="none" stroke="#598f7b" stroke-width="5" stroke-linecap="round"/><path d="M57 80Q31 70 43 49Q61 55 57 80M60 57Q83 45 78 26Q55 31 60 57M31 67Q10 56 18 38Q34 45 31 67M83 77Q105 77 111 55Q92 56 83 77M61 38Q44 22 56 5Q72 14 61 38" fill="#87b497"/><ellipse cx="60" cy="111" rx="25" ry="6" fill="#c1c5a0"/>'};return `<svg viewBox="0 0 125 125" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">${shapes[type]}</svg>`}
const creatures=[{name:'Морская звезда',type:'star',habitat:'НА ДНЕ У СКАЛИСТОГО БЕРЕГА',text:'Морские звёзды перемещаются по дну. В учебнике они показаны среди обитателей скалистых берегов — рядом с морскими ежами, водорослями и крабами.'},{name:'Медуза',type:'jelly',habitat:'В ТОЛЩЕ ВОДЫ',text:'Медузы встречаются в толще воды. Их прозрачное желеобразное тело похоже на шляпку гриба. Упомянутая в учебнике цианея может иметь купол диаметром до двух метров. Медуз не трогают: можно обжечься.'},{name:'Рыбы',type:'fish',habitat:'СРЕДИ ПОДВОДНЫХ ЗАРОСЛЕЙ',text:'Вдали от берега встречаются подводные заросли водорослей. Между их длинными колышущимися лентами проплывают стайки рыб.'},{name:'Краб',type:'crab',habitat:'В ЩЕЛЯХ И ТРЕЩИНАХ',text:'У скалистых берегов крабы прячутся в щелях и трещинах. На песчаном берегу многие ракообразные и моллюски при опасности зарываются в песок.'},{name:'Актиния',type:'anemone',habitat:'ПРИКРЕПЛЯЕТСЯ К КАМНЯМ',text:'Актиния похожа на цветок, но это животное. Она крепко держится на камне, а щупальцами ловит добычу.'},{name:'Водоросли',type:'kelp',habitat:'НА КАМНЯХ И ПОД ВОДОЙ',text:'У скалистых берегов камни покрыты водорослями. Они прочно прикрепляются к камням и выдерживают волны. У песчаных берегов в параграфе описана морская трава — это не водоросли.'}];
$('#creature-grid').innerHTML=creatures.map((c,i)=>`<button class="creature-button" data-creature="${i}" aria-pressed="false">${creatureSVG(c.type)}${c.name}</button>`).join('');$$('[data-creature]').forEach(b=>b.onclick=()=>selectCreature(+b.dataset.creature));function selectCreature(i){let c=creatures[i];$$('[data-creature]').forEach(b=>{b.classList.toggle('active',+b.dataset.creature===i);b.setAttribute('aria-pressed',+b.dataset.creature===i)});$('#creature-art').innerHTML=creatureSVG(c.type);$('#creature-habitat').textContent=c.habitat;$('#creature-name').textContent=c.name;$('#creature-text').textContent=c.text}
$('#underwater').innerHTML=`<svg viewBox="0 0 700 330" preserveAspectRatio="xMidYMid slice"><defs><linearGradient id="sea" x2="0" y2="1"><stop stop-color="#0c6375"/><stop offset="1" stop-color="#063b50"/></linearGradient></defs><rect width="700" height="330" fill="url(#sea)"/><path d="M340 0L220 330H300L410 0M495 0L405 330H455L535 0" fill="#b8e6d7" opacity=".035"/><path d="M0 310Q130 278 250 310T490 301T700 319V330H0Z" fill="#547f79"/><g transform="translate(360,40) scale(1.2)">${creatureSVG('jelly')}</g><g transform="translate(190,155) scale(.9)">${creatureSVG('fish')}</g><g transform="translate(70,213) scale(.9)">${creatureSVG('kelp')}</g><g transform="translate(535,204) scale(1)">${creatureSVG('kelp')}</g><g transform="translate(377,248) scale(.65)">${creatureSVG('star')}</g><g fill="none" stroke="#b2dbda" opacity=".32"><circle cx="350" cy="110" r="4"/><circle cx="333" cy="70" r="6"/><circle cx="563" cy="90" r="3"/><circle cx="206" cy="250" r="4"/></g></svg>`;
const questions=[
 {q:'Что называют Мировым океаном?',options:['Только самые глубокие участки воды','Основную часть гидросферы, включающую воды океанов и морей','Все реки и озёра Земли','Только воду вокруг Антарктиды'],answer:1,why:'Мировой океан — единое водное пространство, включающее океаны и моря. Все океаны сообщаются между собой.',section:'oceans'},
 {q:'Какой океан самый большой и самый глубокий?',options:['Тихий','Атлантический','Индийский','Северный Ледовитый'],answer:0,why:'Тихий океан занимает почти половину площади Мирового океана и является самым глубоким.',section:'oceans'},
 {q:'Как правильно расположить океаны от большего к меньшему?',options:['Атлантический → Тихий → Индийский → Северный Ледовитый','Тихий → Индийский → Атлантический → Северный Ледовитый','Тихий → Атлантический → Индийский → Северный Ледовитый','Индийский → Тихий → Северный Ледовитый → Атлантический'],answer:2,why:'По данным учебника: 178,6 → 91,6 → 76,2 → 14,7 млн км².',section:'compare'},
 {q:'Какой океан почти целиком расположен в Южном полушарии?',options:['Северный Ледовитый','Атлантический','Тихий','Индийский'],answer:3,why:'Индийский океан почти целиком расположен к югу от экватора.',section:'oceans'},
 {q:'Какое из этих морей — окраинное?',options:['Чёрное','Баренцево','Красное','Средиземное'],answer:1,why:'Баренцево море находится у окраины материка. Остальные три моря приведены в параграфе как внутренние.',section:'coasts'},
 {q:'Часть океана или моря, вдающаяся в сушу, — это…',options:['Залив','Остров','Материк','Пролив'],answer:0,why:'Залив — часть моря или океана, которая вдаётся в сушу.',section:'coasts'},
 {q:'Что делает пролив?',options:['Соединяет участки суши','Всегда отделяет море от океана','Соединяет акватории и разделяет участки суши','Представляет собой замкнутый водоём'],answer:2,why:'У пролива две роли: он соединяет водные пространства и разделяет участки суши.',section:'coasts'},
 {q:'Какие океаны соединяет Берингов пролив?',options:['Атлантический и Индийский','Индийский и Тихий','Атлантический и Северный Ледовитый','Тихий и Северный Ледовитый'],answer:3,why:'Берингов пролив соединяет Тихий и Северный Ледовитый океаны, разделяя Евразию и Северную Америку.',section:'coasts'},
 {q:'Чем необычно Саргассово море?',options:['В нём пресная вода','Оно расположено между течениями','Оно находится на Северном полюсе','Это самое маленькое озеро'],answer:1,why:'Саргассово море находится в Атлантическом океане между течениями. У него нет привычных берегов из суши.',section:'coasts'},
 {q:'Актиния похожа на цветок. Кто она на самом деле?',options:['Морское животное','Водоросль','Морская трава','Камень'],answer:0,why:'Актиния — животное. Она прикрепляется к камню и ловит добычу щупальцами.',section:'life'}
];
let qi=0,answers=[],best=0;try{let n=Number(localStorage.getItem('world-ocean-v2-best'));if(Number.isFinite(n)&&n>=0&&n<=10)best=n}catch{}
function renderQuiz(){let done=qi>=questions.length;$('#quiz-counter').textContent=done?'Экспедиция завершена':`Вопрос ${qi+1} из ${questions.length}`;$('#quiz-best').textContent=best?`Лучший результат: ${best} / 10`:'Твой первый маршрут';$('#quiz-progress').style.width=`${qi/questions.length*100}%`;if(done){let score=answers.filter((a,i)=>a===questions[i].answer).length;let misses=[...new Set(questions.filter((q,i)=>answers[i]!==q.answer).map(q=>q.section))];let names={oceans:'Океаны',compare:'Размеры',coasts:'Берега',life:'Жизнь'};$('#quiz-body').innerHTML=`<div class="result"><p class="eyebrow">ТВОЙ РЕЗУЛЬТАТ</p><div class="result-score">${score}<span style="font-size:32px;color:#8ba49e"> / 10</span></div><h2>${score===10?'Отличный курс!':score>=7?'Хорошая экспедиция!':'Продолжим исследование?'}</h2><p>${score===10?'Ты умеешь различать части Мирового океана и ориентируешься в главных понятиях.':'Ошибки помогают заметить то, что стоит повторить. Вернись к нужным разделам и попробуй ещё раз.'}</p><div class="result-revisit">${misses.map(s=>`<button class="text-btn" data-review="${s}">Повторить: ${names[s]} ↗</button>`).join('')}</div><button class="primary" id="quiz-restart">Пройти ещё раз ↺</button></div>`;$('#quiz-restart').onclick=()=>{qi=0;answers=[];renderQuiz()};$$('[data-review]').forEach(b=>b.onclick=()=>go(b.dataset.review));return}let q=questions[qi],answered=answers[qi]!==undefined;$('#quiz-body').innerHTML=`<h2 class="quiz-question">${q.q}</h2><div class="quiz-options">${q.options.map((o,i)=>`<button class="quiz-option ${answered&&i===q.answer?'correct':''} ${answered&&i===answers[qi]&&i!==q.answer?'wrong':''}" data-answer="${i}" ${answered?'disabled':''}><span>${'АБВГ'[i]}</span>${o}</button>`).join('')}</div><div id="quiz-feedback" aria-live="polite">${answered?feedback(q):''}</div>`;$$('[data-answer]').forEach(b=>b.onclick=()=>{if(answers[qi]!==undefined)return;answers[qi]=+b.dataset.answer;renderQuiz()});if(answered)$('#quiz-next').onclick=()=>{qi++;if(qi===questions.length){let score=answers.filter((a,i)=>a===questions[i].answer).length;best=Math.max(best,score);try{localStorage.setItem('world-ocean-v2-best',String(best))}catch{}}renderQuiz();$('#quiz-body').scrollIntoView({block:'nearest',behavior:'smooth'});$('#quiz-next')?.focus()}}
function feedback(q){let right=answers[qi]===q.answer;return `<div class="feedback ${right?'':'wrong'}"><strong>${right?'Верно!':'Разберёмся вместе'}</strong>${q.why}</div><button class="primary quiz-next" id="quiz-next">${qi===questions.length-1?'Посмотреть результат':'Следующий вопрос'} →</button>`}
selectOcean(0);selectCoast(0);selectStrait(0);selectCreature(0);renderQuiz();go(['oceans','compare','coasts','model','life','quiz'].includes(location.hash.slice(1))?location.hash.slice(1):'oceans');
