'use strict';
(()=>{
 const host=document.getElementById('model-canvas'),labels=document.getElementById('model-labels');
 let renderer,scene,camera,model,frame=0,angle=.52,elevation=.9,distance=13.8,drag=null,feature='all';
 const highlights={},markers=[];let autoRotate=true,autoFrame=0,autoLast=0; function autoTick(t){if(document.hidden||document.getElementById('model').hidden){autoFrame=0;autoLast=0;return}let dt=autoLast?Math.min((t-autoLast)/1000,.05):0;autoLast=t;if(autoRotate&&!drag){angle+=dt*.12;render()}autoFrame=requestAnimationFrame(autoTick)}function startAuto(){if(!autoFrame&&!document.hidden&&!document.getElementById('model').hidden){autoLast=0;autoFrame=requestAnimationFrame(autoTick)}}document.getElementById('model-auto').onclick=()=>{autoRotate=!autoRotate;document.getElementById('model-auto').textContent=autoRotate?'⏸ Пауза':'▶ Вращать';document.getElementById('model-auto').setAttribute('aria-pressed',String(autoRotate));startAuto()};document.addEventListener('visibilitychange',startAuto);
 const info={all:['Одна береговая линия — три понятия','Золотые контуры выделяют море, залив и пролив. Выбери объект, чтобы оставить только его выделение. Вода во всех частях модели связана.'],sea:['Море глубоко вдаётся в сушу','Здесь показано внутреннее море: суша окружает большую часть его берегов. С открытым океаном оно связано узким проливом.'],bay:['Залив вдаётся в берег','Посмотри на южный изгиб берега: океан входит в сушу широкой водной выемкой. Это залив. Он открыт в сторону океана.'],strait:['Пролив соединяет воды','Узкая полоса воды соединяет внутреннее море с океаном. Одновременно она разделяет два участка суши. Поверни модель, чтобы проследить этот проход.']};
 function signedLand(x,z){let coast=.7+.28*Math.sin(z*1.5)-x;let sea=Math.sqrt(((x+2.3)/1.45)**2+(z/1.1)**2)-1;let channel=Math.max(Math.abs(z)-.25,-x-2.3,x-1.5);let bay=Math.sqrt(((x-.35)/1.4)**2+((z-2.25)/.87)**2)-1;return Math.min(coast,sea*1.1,channel,bay*.87)}
 function init(){if(renderer)return;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xdef1ed,1);host.appendChild(renderer.domElement)}catch(e){host.innerHTML='<p class="webgl-fallback">В этом браузере 3D недоступно. Открой раздел «Берега»: там те же понятия показаны на интерактивных схемах.</p>';return}
  scene=new THREE.Scene();scene.fog=new THREE.Fog(0xdef1ed,22,45);camera=new THREE.PerspectiveCamera(39,1,.1,60);model=new THREE.Group();scene.add(model);scene.add(new THREE.HemisphereLight(0xf5ffff,0x597c6c,.7));let sun=new THREE.DirectionalLight(0xffefca,.55);sun.position.set(-4,10,7);scene.add(sun);
  let base=new THREE.Mesh(new THREE.BoxGeometry(11.8,.42,8.4),new THREE.MeshStandardMaterial({color:0x287f92,roughness:.8}));base.position.y=-.39;model.add(base);
  let terrain=new THREE.PlaneGeometry(11.8,8.4,176,124);terrain.rotateX(-Math.PI/2);let pos=terrain.attributes.position,colors=[];for(let i=0;i<pos.count;i++){let x=pos.getX(i),z=pos.getZ(i),d=signedLand(x,z);let h=d>0?.12+Math.min(d,.5)*.55+Math.max(0,Math.sin(x*1.3+1)*Math.cos(z*.9))*.38*Math.min(1,d*2):-.25;pos.setY(i,h);let c=new THREE.Color(d<0?0x7bbbb7:d<.12?0xe2d3a0:h>.55?0x749664:0x9eb778);colors.push(c.r,c.g,c.b)}terrain.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));terrain.computeVertexNormals();let land=new THREE.Mesh(terrain,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1,side:THREE.DoubleSide}));model.add(land);
  let water=new THREE.Mesh(new THREE.PlaneGeometry(11.8,8.4),new THREE.MeshStandardMaterial({color:0x238faa,transparent:true,opacity:.78,roughness:.32,metalness:.13}));water.rotation.x=-Math.PI/2;water.position.y=.06;model.add(water);
  const lineMaterial=new THREE.LineBasicMaterial({color:0xffdb86,transparent:true,opacity:.98});
  function curve(name,points){let group=highlights[name]||(highlights[name]=new THREE.Group());if(!group.parent)model.add(group);let g=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(p[0],.13,p[1])));group.add(new THREE.Line(g,lineMaterial))}
  curve('sea',Array.from({length:81},(_,i)=>{let a=i/80*Math.PI*2;return[-2.3+1.26*Math.cos(a),.93*Math.sin(a)]}));
  curve('bay',Array.from({length:65},(_,i)=>{let a=Math.PI/2+i/64*Math.PI;return[.35+1.16*Math.cos(a),2.25+.7*Math.sin(a)]}));
  curve('strait',[[-1.05,0],[1.8,0]]);curve('strait',[[1.45,-.15],[1.8,0],[1.45,.15]]);curve('strait',[[-.7,-.15],[-1.05,0],[-.7,.15]]);
  for(let i=0;i<27;i++){let x=-5.3+(i%7)*.85,z=-3.5+Math.floor(i/7)*1.85;if(signedLand(x,z)<.35)continue;let d=signedLand(x,z),h=.12+Math.min(d,.5)*.55+Math.max(0,Math.sin(x*1.3+1)*Math.cos(z*.9))*.38*Math.min(1,d*2);let tree=new THREE.Mesh(new THREE.ConeGeometry(.1,.35,6),new THREE.MeshStandardMaterial({color:i%2?0x42775c:0x54886b,roughness:1}));tree.position.set(x,h+.17,z);model.add(tree)}
  [['sea','Море',-2.3,.3,0],['bay','Залив',-.35,.3,2.25],['strait','Пролив',.1,.3,0],['ocean','Океан',3.5,.2,.2],['land','Суша',-3.7,.8,-2.3]].forEach(([id,title,x,y,z])=>{let el=document.createElement('span');el.className='model-label';el.textContent=title;el.dataset.feature=id;labels.appendChild(el);markers.push({id,el,p:new THREE.Vector3(x,y,z)})});
  resize();render();startAuto();
 }
 function resize(){if(!renderer||document.getElementById('model').hidden)return;let r=host.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();render()}
 function render(){if(!renderer||document.getElementById('model').hidden)return;let fitted=distance*Math.max(1,1.5/camera.aspect);camera.position.set(Math.sin(angle)*Math.cos(elevation)*fitted,Math.sin(elevation)*fitted,Math.cos(angle)*Math.cos(elevation)*fitted);camera.lookAt(0,0,0);renderer.render(scene,camera);let r=host.getBoundingClientRect();markers.forEach(m=>{let p=m.p.clone().project(camera);m.el.style.left=((p.x+1)/2*r.width)+'px';m.el.style.top=((-p.y+1)/2*r.height)+'px';m.el.classList.toggle('selected',m.id===feature);m.el.hidden=feature!=='all'&&!['land','ocean',feature].includes(m.id)});}
 function choose(key){feature=key;Object.entries(highlights).forEach(([k,g])=>g.visible=key==='all'||key===k);document.querySelectorAll('[data-feature]').forEach(b=>{if(b.tagName==='BUTTON'){b.classList.toggle('active',b.dataset.feature===key);b.setAttribute('aria-pressed',b.dataset.feature===key)}});document.getElementById('model-feature-title').textContent=info[key][0];document.getElementById('model-feature-text').textContent=info[key][1];render()}
 document.querySelectorAll('#model-choices button').forEach(b=>b.onclick=()=>{init();choose(b.dataset.feature)});
 host.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,angle,elevation};host.setPointerCapture(e.pointerId);host.classList.add('dragging')});host.addEventListener('pointermove',e=>{if(!drag)return;angle=drag.angle-(e.clientX-drag.x)*.008;elevation=Math.max(.43,Math.min(1.4,drag.elevation+(e.clientY-drag.y)*.005));render()});function release(){drag=null;host.classList.remove('dragging')}host.addEventListener('pointerup',release);host.addEventListener('pointercancel',release);
 host.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(9,Math.min(22,distance+e.deltaY*.01));render()},{passive:false});document.getElementById('model-plus').onclick=()=>{distance=Math.max(9,distance-1.5);render()};document.getElementById('model-minus').onclick=()=>{distance=Math.min(22,distance+1.5);render()};document.getElementById('model-reset').onclick=()=>{angle=.52;elevation=.9;distance=13.8;choose('all');render()};
 new ResizeObserver(resize).observe(host);new MutationObserver(()=>{if(!document.getElementById('model').hidden){if(!renderer){distance=13.8;init()}requestAnimationFrame(resize);startAuto()}}).observe(document.getElementById('model'),{attributes:true,attributeFilter:['hidden']});if(!document.getElementById('model').hidden)init();
})();
