'use strict';
(()=>{
 const photos={star:{file:'star.jpg',alt:'Синяя морская звезда на морском дне',credit:'dr.scott.mills · CC BY-SA 2.0',source:'https://commons.wikimedia.org/wiki/File:Linckia_laevigata_Tonga.jpg',license:'https://creativecommons.org/licenses/by-sa/2.0/'},jelly:{file:'jelly.jpg',alt:'Золотистая медуза в синей воде',credit:'Dan90266 · CC BY-SA 2.0',source:'https://commons.wikimedia.org/wiki/File:Jelly_cc11.jpg',license:'https://creativecommons.org/licenses/by-sa/2.0/'},fish:{file:'reef-noaa.png',alt:'Морские рыбы над коралловым рифом',credit:'NOAA Fisheries / Dani Escontrola',source:'https://www.fisheries.noaa.gov/gallery/monitoring-coral-reefs-hawaii'},crab:{file:'crab.jpg',alt:'Морской краб с крупными клешнями',credit:'Hans Hillewaert · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Cancer_pagurus.jpg',license:'https://creativecommons.org/licenses/by-sa/4.0/'},anemone:{file:'anemone.jpg',alt:'Морская актиния с раскрытыми щупальцами',credit:'Nick Hobgood · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Entacmaea_quadricolor_(Bubble_tip_anemone).jpg',license:'https://creativecommons.org/licenses/by-sa/3.0/'},kelp:{file:'kelp.jpg',alt:'Золотисто-коричневые морские водоросли',credit:'Bjørn Christian Tørrissen · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Kelp_In_Freycinet_Tasmania.jpg',license:'https://creativecommons.org/licenses/by-sa/3.0/'}};
 function photo(type){const p=photos[type];return `<img src="assets/${p.file}" alt="${p.alt}" width="700" height="525" loading="lazy">`}
 document.querySelectorAll('[data-creature]').forEach(b=>{const type=creatures[+b.dataset.creature].type;b.querySelector('svg')?.remove();b.insertAdjacentHTML('afterbegin',photo(type));b.addEventListener('click',()=>show(+b.dataset.creature))});
 function show(i){const p=photos[creatures[i].type];document.getElementById('creature-art').innerHTML=`<figure>${photo(creatures[i].type)}<figcaption><a href="${p.source}" target="_blank" rel="noopener">${p.credit}</a>${p.license?` · <a href="${p.license}" target="_blank" rel="noopener">Лицензия</a>`:''}</figcaption></figure>`}
 show(0);
 const note=document.createElement('p');note.innerHTML='<b>Фотографии обитателей:</b> Wikimedia Commons и NOAA. Автор, источник и лицензия указаны под выбранной фотографией. Снимки показывают представителей групп; фотография медузы не обозначает именно цианею.';document.getElementById('sources-dialog').appendChild(note);
})();
